apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-seguridad-deploy
  labels:
    app: microservice-seguridad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-seguridad
  template:
    metadata:
      labels:
        app: microservice-seguridad
    spec:
      containers:
      - name: microservicio-seguridad
        image: diananldd/serviciosapiseguridad:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__ConexionDB
          value: Server=mssql-service;Database=Seguridad;User=sa;Password=$DianaLpz
