apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice 
spec: 
  containers:
  - name: microservicio-seguridad
    image: diananldd/serviciosapiseguridad:latest
    ports:
      - containerPort: 80
    env:
      - name: ConnectionStrings__ConexionDB
        value: Server=mssql-service:Database=Seguridad;User=sa;Password=$DianaLpz