apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-libreria-deploy
  labels:
    app: microservice-libreria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-libreria
  template:
    metadata:
      labels:
        app: microservice-libreria
    spec:
      containers:
      - name: microservicio-libreria
        image: diananldd/serviciosapilibreria:latest
        ports:
        - containerPort: 80
        env:
        - name: MongoDb__ConnectionString
          value: mongodb://DianaLpz:$DianaLpz2025@mongo-service:27017
