apiVersion: apps/v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
    app: database
spec:
  type: LoadBalancer
  ports:
   - port: 27017 
     targetPort: 27017
  selector: 
    app: microservicio-libreria
    name: mongo-pod


   

