apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mssql-deploy
  labels:
    app: microservice-seguridad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-seguridad
      name: mssql-pod
  template:
    metadata:
      labels:
        app: microservice-seguridad
        name: mssql-pod
    spec: 
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "$DianaLpz"


